Core_SSH_Variables:
  CLIUserName: root
  Command_For_ChangeUser: sudo -i
  Command_For_Validate_User: whoami
  Password: Netprizm@2023
  SUTENV: qa2
  ServerIP: 10.30.249.221
  UserName: vzqa
Environment_Variables:
  EnvName: Ashburn-QA
  HostName: 10.30.249.244
  UserName: vzqa
Log_Files_Name:
  CoreFileName: 'qa2corepodslog.txt '
  OutFileInJson: qa2VersionsOutput.json
  SSH_LogFile: qa2extractVersionsInput.txt
  SSH_LogFile_AfterFilter: qa2extractVersionsInput2.txt
SSH_Variables:
  CLIUserName: vzqa
  CLI_Binary_Name: np2-cli-tool.sh
  CLI_Binary_Path: /opt/netprizm2/cli/np2-cli-tool.sh
  CLI_Directory: /opt/netprizm2/cli
  CLI_Run_Command: ./np2-cli-tool.sh
  Command_For_ChangeUser: sudo -i
  Command_For_Validate_User: whoami
  EnvName: qa2
  Exit_From_CLI_Command: q
  Modules_Version_Check_Command: v
  Password: Netprizm@2023
  Path_Of_CLI_Directory: cd /opt/netprizm2/cli
  ServerIP: 10.30.249.244
  UserName: vzqa
